### ISSUE TITLE
Making folders

### ISSUE THREAD

**Issue by r3dhat** [FUCKYESISLIFE/RebooterApp#1]
Just in case you're wondering, yes, you can make folders on GitHub. It's hidden in the UI. 

While making a new file, just type a forward slash after what you're typing and it should let you make a file within that folder. I highly recommend just syncing using something like Xcode (I'm not too used to Xcode but I believe it makes a Git repository automatically) or manually using `git`.

**Comment by FUCKYESISLIFE** [comment]
right. didn't understand that. sorry, just GitHub is very very new to me, so not really very used to its platform yet. thank you anyway bud.
